# Generated by Django 5.2.1 on 2025-07-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('products', models.CharField(max_length=200)),
                ('feedback', models.TextField(blank=True)),
                ('has_coupon', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usersurvey',
            },
        ),
    ]
