# Generated by Django 5.2.1 on 2025-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
