# Generated by Django 5.2.1 on 2025-06-14 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_student_year_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='SwiggyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swiggy_user', to='demo.wallet')),
            ],
            options={
                'db_table': 'swiggy_user',
            },
        ),
    ]
