# Generated by Django 5.2.1 on 2025-06-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_freelancer_project_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='project',
            name='freelancer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.freelancer'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.project'),
        ),
    ]
