# Generated by Django 5.2.1 on 2025-06-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_remove_bid_freelancer_project_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.freelancer'),
        ),
    ]
