# Generated by Django 5.2.1 on 2025-06-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_alter_project_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='bid',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.freelancer'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
