# Generated by Django 5.2.1 on 2025-07-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_remove_project_freelancer_bid_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('freelancer', 'project')},
        ),
    ]
