# Generated by Django 5.2.1 on 2025-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('joining', models.BooleanField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'employee1',
            },
        ),
    ]
