# Generated by Django 5.2.1 on 2025-07-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
